<?php
/** @var $this StudioForty9_Schema_Block_Product_Grouped */
$currency_code = $this->getCurrencyCode();
$currency_symbol = $this->getCurrencySymbol($currency_code);
$products = $this->getAssociatedProducts();
?>
<div class="product-schema hide" itemscope itemtype="http://schema.org/Product" style="display: none;">

    <?php echo $this->getChildHtml('information'); ?>

    <div itemprop="offers" itemscope itemtype="http://schema.org/AggregateOffer">
        <?php
        /** @var Mage_Catalog_Model_Product $item */
        foreach ($products as $item) :

            $name = Mage::helper('core')->escapeHtml($item->getName());
            $url = $item->getProductUrl(false);
            $price = $this->getPrice($item);
            ?>
            <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <span itemprop="name"><?php echo $name; ?></span>
                <span itemprop="priceCurrency" content="<?php echo $currency_code; ?>"><?php echo $currency_symbol; ?></span>
                <span itemprop="price" content="<?php echo $price; ?>"><?php echo $price; ?></span>
                <a itemprop="url" href="<?php echo $url; ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a>
                <?php if ($item->isSaleable()): ?>
                    <link itemprop="availability" href="http://schema.org/InStock"/>
                <?php else : ?>
                    <link itemprop="availability" href="http://schema.org/OutOfStock"/>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>

        <span itemprop="lowPrice"><?php echo $currency_symbol . $this->getLowestPrice(); ?></span>
        <?php echo $this->__('to') ?>
        <span itemprop="highPrice"><?php echo $currency_symbol . $this->getHighestPrice(); ?></span>
    </div>

    <?php echo $this->getChildHtml('additional'); ?>
</div>
