<?php
/** @var $this StudioForty9_Schema_Block_Product */
/** @var Mage_Catalog_Model_Product $product */
$product = $this->getProduct();
$currency_code = $this->getCurrencyCode();
$currency_symbol = $this->getCurrencySymbol($currency_code);
$price = $this->getPrice($product);
?>
<div class="product-schema hide" itemscope itemtype="http://schema.org/Product" style="display: none;">

    <?php echo $this->getChildHtml('information'); ?>

    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        <span itemprop="priceCurrency" content="<?php echo $currency_code; ?>"><?php echo $currency_symbol; ?></span>
        <span itemprop="price" content="<?php echo $price; ?>"><?php echo $price; ?></span>
        <?php if($product->isAvailable()): ?>
            <link itemprop="availability" href="http://schema.org/InStock" />
        <?php else : ?>
            <link itemprop="availability" href="http://schema.org/OutOfStock" />
        <?php endif; ?>
    </div>

    <?php echo $this->getChildHtml('ratings'); ?>

    <?php echo $this->getChildHtml('additional'); ?>
</div>
