<?php
/** @var $this Studioforty9_Schema_Block_Cms_Page */
$headline = $this->getHeadline();
$created = $this->getCreatedDate();
$modified = $this->getModifiedDate();
?>
<div class="product-schema hide" itemscope itemtype="http://schema.org/Article" style="display: none;">
    <span itemprop="name"><?php echo $this->getTitle(); ?></span>
    <?php if ($headline): ?>
    <span itemprop="headline"><?php echo $headline; ?></span>
    <?php endif; ?>
    <span itemprop="description"><?php echo $this->getDescription(); ?></span>
    <time datetime="<?php echo $created; ?>" itemprop="datePublished"><?php echo $this->formatSchemaDate($created); ?>/time>
    <time datetime="<?php echo $created; ?>" itemprop="dateCreated"><?php echo $this->formatSchemaDate($created); ?>/time>
    <time datetime="<?php echo $modified; ?>" itemprop="dateModified"><?php echo $this->formatSchemaDate($modified); ?>/time>
    <?php echo $this->getChildHtml('additional'); ?>
</div>